config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :brands
  resources :payouts
  resources :artists
  resources :uploads
  resources :categories
  resources :bookings
  resource :dashboard do
    resource :profile, :controller => 'dashboards', :action => 'profile'
    resource :account, :controller => 'dashboards', :action => 'account'
    resource :bookings, :controller => 'dashboards', :action => 'bookings'
  end
  resources :purchases
  resources :messages

  root to: 'visitors#landing'
  get 'visitors/index', :to => 'visitors#index'

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  ActiveAdmin.routes(self)
  mount_griddler

  # SEO stuff
  get 'event/:url_fragment', :controller => 'brands', :action => 'show', :as => 'nice_brand'
  get ':artist_name', :controller => 'artists', :action => 'show', :as => 'nice_artist'
  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def landing
    @performers = Artist.approved.limit(12)
    @brands = Brand.limit(3)
    @totals = {}
    Purchase.all.each do |p|
      @totals[p.price_json['currency']] ||= 0
      @totals[p.price_json['currency']] += p.price_json['take']
    end
  end

end

app/views/visitors/index.html.haml
.section.welcome
  .wrapped
    %h2 We pull you through.
    %p End the stupid. Get live video & chat sessions with people in the know.
    %p [See how it works]
    %p [100% money back guarantee]
.section.categories
  .wrapped
    %h2 Have a dream? We help you make it a reality!
    %h2 Have a problem? We help you fix it!
    %p
      - Category.all.each do |cat|
        = link_to cat.name, cat
    %p= link_to 'Browse all categories', categories_path


.section.initial_signup
  .wrapped
    %h2 Join the community as expert!
    %p Discover the easiest way to schedule sessions with students and clients.
    .block
      %form{:action => new_user_registration_path}
        .hi
          Hi,
        .name
          my name is
          %input(name="name" placeholder="deadmau5")
        .artist
          and I am
          %input(name="artist" placeholder="teaching music production")
        .category
          in the category
          %select(name="category")= options_from_collection_for_select(Category.all, :id, :name)
        %button Sign up as expert
.section.statistics
  .wrapped
    %h2 We connect those who are eager to learn with those who are eager to teach.
    .block
      %p
        %strong= User.count
      %p Members
    .block
      %p
        %strong= User.count
      %p Sessions held
    .block
      %p
        %strong $#{User.count}
      %p Earned

app/views/visitors/landing.html.haml
.section.landing_head
  .container
    .big= t '.tagline'
    .small= t '.tagline2'
    -# %p
    -#   %i.fa.fa-play
    -#   = t '.explain'
  -# .search_box
  -#   .contfainer<
  -#     %span.part.first>= t "I'm looking for"
  -#     %select.part.select2.category(name="category" data-search="false")= options_from_collection_for_select(Category.all, :id, :name)
  -#     %span.part.event>= t 'for an event on'
  -#     %input.part.datepicker>
  -#     %button= t 'Search'
  .bottom
    = link_to t('.join_now'), new_user_registration_path, :class => 'get_started btn btn-lg btn-primary'
    .more
      = t 'Browse'
      %br
      .caret

.section.featured_bookable
  .container
    .row
      - @performers.each do |performance|
        .col-sm-6.col-md-4
          .embed-responsive.embed-responsive-4by3.artist_cell
            = link_to nice_artist_url(performance.url_fragment) do
              .artist.embed-responsive-item{:style => "background-image: url(#{performance.image&.thumb('400x300#')&.url})"}
                .gradient
                .details
                  .pic_circle
                    - if performance.profile_image
                      .pic_image{:style => "background-image: url(#{performance.profile_image.thumb('74x74#').url})"}
                  .name
                    = performance.name
                  .pricing
                    %span.category
                      %span.category-icon{:class => performance.category_id} 
                      #{performance.category.name}
-# .section.call_to_actions
-#   .container
    
-#     %h1= t('.for_djs')
-#     = t('.for_djs_html')
-#     %p
-#       = link_to t('.list_a_dj'), new_user_registration_path, :class => 'btn btn-lg btn-primary'
      -# .col-sm-6.for_events
      -#   %h1= t('.for_events')
      -#   = t('.for_events_html')
      -#   %p
      -#     = link_to t('.list_an_event'), new_user_registration_path, :class => 'btn btn-lg btn-primary'
    -# .others
    -#   = t('.other_services')
    -#   = link_to t('.find_out_more'), page_path('services')
-# .section.statistics
-#   .container
-#     %h1= t '.statistics'
-#     = t '.earnings_till_date'
-#     - @totals.each do |currency, amount|
-#       .total
-#         %strong= nice_price Price.new(:currency => currency, :take => amount)
-#     = t '.earnings_till_date2'      
-# .section.featured_events
-#   .container
-#     %h1= t '.upcoming_tagline'
-#     %h2= t '.upcoming_tagline2'
-#     .row
-#       - @brands.each do |brand|
-#         .col-xs-12
-#           = link_to nice_brand_url(brand.url_fragment) do
-#             .event_brand{:style => "background-image: url(#{brand.image&.thumb('600x250#')&.url})"}
-#               .gradient
-#               .details
-#                 .name
-#                   = brand.name
    
    