config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :brands
  resources :payouts
  resources :artists
  resources :uploads
  resources :categories
  resources :bookings
  resource :dashboard do
    resource :profile, :controller => 'dashboards', :action => 'profile'
    resource :account, :controller => 'dashboards', :action => 'account'
    resource :bookings, :controller => 'dashboards', :action => 'bookings'
  end
  resources :purchases
  resources :messages

  root to: 'visitors#landing'
  get 'visitors/index', :to => 'visitors#index'

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  ActiveAdmin.routes(self)
  mount_griddler

  # SEO stuff
  get 'event/:url_fragment', :controller => 'brands', :action => 'show', :as => 'nice_brand'
  get ':artist_name', :controller => 'artists', :action => 'show', :as => 'nice_artist'
  
end

app/views/user_notifier/admin_new_listing.text.erb
New listing awaits a approval:

===========================
<%= @artist.name %>
<%= artist_url(@artist) %>
===========================

app/views/user_notifier/booking_confirmed.text.erb
Hello <%= @user.display_name %>,

good news! <%= @artist.name %> confirmed your booking request!

Please visit the booking page and proceed with the payment.
<%= booking_url(@booking) %>

We will provide you with further information once the payment has been received.

app/views/user_notifier/booking_declined.text.erb
Hello <%= @user.display_name %>,

<%= @artist.name %> has declined your booking request.

Feel free to open a new booking request with us any time in the future.

app/views/user_notifier/booking_inquiry.text.erb
Hello <%= @user.display_name %>,

<%= @booking.user.display_name %> wants to book <%= @artist.name %>.

A new booking request has been opened. Please check and confirm availability:
<%= booking_url(@booking) %>

After you confirm, you will be able to receive payment.

app/views/user_notifier/booking_inquiry_for_management.text.erb
Hello <%= @user.display_name %>,

<%= @booking.user.display_name %> wants to book <%= @artist.name %>.

A new booking request has been opened. Please check and confirm availability:
<%= booking_url(@booking) %>

After you confirm, you will be able to receive payment.

app/views/user_notifier/booking_payment_completed.text.erb
Hello <%= @user.display_name %>,

thank you for booking <%= @artist.name %> through Audissey.

This is your booking confirmation.

Event Date: <%= @booking.start_at %>

Please use the following information to contact <%= @artist.name %> directly:

=============================
<%= @artist.contact_details %>
=============================

Thank you for using Audissey!
We hope you have a good experience.

Feel free to reply to this email in case of problems.

app/views/user_notifier/booking_payment_received.text.erb
Hello <%= @user.display_name %>,

you have received payment for <%= @artist.name %>.

Event Date: <%= @booking.start_at %>

Please note that you are now responsible for the availability of <%= @artist.name %> on the designated date.

We forwarded your information to the buyer. You can check the details on the booking page.
<%= booking_url(@booking) %>

The buyer should contact you soon.

Thank you for using Audissey!
We hope you have a good experience.

Feel free to reply to this email in case of problems.

app/views/user_notifier/booking_payment_received_for_management.text.erb
Hello <%= @user.display_name %>,

you have received payment for <%= @artist.name %>.

Event Date: <%= @booking.start_at %>

Please note that you are now responsible for the availability of <%= @artist.name %> on the designated date.

We forwarded your contact details to the buyer. You can check the details on the booking page.
<%= booking_url(@booking) %>

The buyer should contact you soon.

Thank you for using Audissey!
We hope you have a good experience.

Feel free to reply to this email in case of problems.

app/views/user_notifier/message_received.text.erb
-- REPLY ABOVE THIS LINE --

<%= @message.text %>

<%- if @booking -%>
========================
You can reply to this message directly or view the conversation and event details here: <%= booking_url(@booking) %>
<%- end -%>