config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :brands
  resources :payouts
  resources :artists
  resources :uploads
  resources :categories
  resources :bookings
  resource :dashboard do
    resource :profile, :controller => 'dashboards', :action => 'profile'
    resource :account, :controller => 'dashboards', :action => 'account'
    resource :bookings, :controller => 'dashboards', :action => 'bookings'
  end
  resources :purchases
  resources :messages

  root to: 'visitors#landing'
  get 'visitors/index', :to => 'visitors#index'

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  ActiveAdmin.routes(self)
  mount_griddler

  # SEO stuff
  get 'event/:url_fragment', :controller => 'brands', :action => 'show', :as => 'nice_brand'
  get ':artist_name', :controller => 'artists', :action => 'show', :as => 'nice_artist'
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @show_guide = true
    @show_guide = false if current_user.artists.any?
    @show_guide = false if current_user.bookings.any?

    

  end
  
  def profile
    render :show
  end
  
  def account
    render :show
  end
  
  def bookings
    bookings_from_me = current_user.bookings
    bookings_with_me = Booking.where(:artist => current_user.artists)
    @all_bookings = (bookings_from_me + bookings_with_me).uniq
    render :show
  end
  
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.haml
= render 'layouts/second_nav'
- if @show_guide
  .section.dashboard_guide
    .container
      %h1 Let's get started.
      = link_to 'Offer your services', new_artist_path, :class => 'btn btn-lg btn-primary'
      or browse our listings

- else
  .section.dashboard
    .container
      - if params[:action] == 'show'
        - if current_user.artists.any?
          .artists
            %h3 Your Listings:
            - current_user.artists.each do |artist|
              = link_to artist.name, artist
              = link_to edit_artist_path(artist) do
                %i.fa.fa-edit
            = link_to t('.new_listing'), new_artist_path, :class => 'btn btn-lg btn-primary'
        
        
      - if params[:action] == 'bookings'
        %h3 Bookings in Progress
        - if @all_bookings.empty?
          Nothing yet
        - @all_bookings.each do |booking|
          .booking
            = link_to booking.artist.name, booking

      - if params[:action] == 'account'
        %h3 Earnings since last Payout
        - current_user.purchases_since_last_payout.each do |purchase|
          .purchase
            #{purchase.created_at.to_s(:short)}: #{nice_price(purchase.price_json)}
            |
            = link_to purchase.buyable do
              #{purchase.buyable}
        
        .payout
        = link_to 'Request Payout', new_payout_path, :class => 'btn btn-primary'
        
        - if current_user.unvalued_purchases.any?
          %h3 Available soon for payout
          - current_user.unvalued_purchases.each do |purchase|
            .purchase
              #{purchase.created_at.to_s(:short)}: #{nice_price(purchase.price_json)}
              |
              = link_to purchase.buyable do
                #{purchase.buyable}
              |
              Available for payout at: #{purchase.value_date.to_s(:short)}
        
        %h3 Payouts
        - current_user.payouts.each do |payout|
          = payout.amounts
          - if payout.completed_at
            %i.fa.fa-checkmark
          - else
            %i.fa.fa-hourglass-half
            Pending
        - if current_user.payouts.empty?
          No payouts to date
        
        %hr  
        = link_to 'Delete Account', current_user, :method => 'delete', 'data-confirm' => 'Are you sure?'
      - if params[:action] == 'profile'
        .settings
          %h3 Account Settings
          = form_for current_user do |f|
            .form-group
              %label Profile Name
              = f.text_field :name, :class => 'form-control'
            .form-group
              %label Email
              = f.text_field :email, :class => 'form-control'
            .form-group
              %label Profile Image
              = f.image_upload_field :image
            .actions
              = f.submit "Save changes.", :class => 'btn btn-lg btn-primary'