config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :brands
  resources :payouts
  resources :artists
  resources :uploads
  resources :categories
  resources :bookings
  resource :dashboard do
    resource :profile, :controller => 'dashboards', :action => 'profile'
    resource :account, :controller => 'dashboards', :action => 'account'
    resource :bookings, :controller => 'dashboards', :action => 'bookings'
  end
  resources :purchases
  resources :messages

  root to: 'visitors#landing'
  get 'visitors/index', :to => 'visitors#index'

  devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  ActiveAdmin.routes(self)
  mount_griddler

  # SEO stuff
  get 'event/:url_fragment', :controller => 'brands', :action => 'show', :as => 'nice_brand'
  get ':artist_name', :controller => 'artists', :action => 'show', :as => 'nice_artist'
  
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  name        :string
#  id          :string           primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  self.primary_key = :id

  delete_all
  find_or_create_by :id => 'performer', :name => 'DJ / Producer'
  find_or_create_by :id => 'lighting', :name => 'VJ / Laser'
  find_or_create_by :id => 'venue', :name => 'Venue'
  find_or_create_by :id => 'photographer', :name => 'Photographer'
  find_or_create_by :id => 'catering', :name => 'Catering'
  find_or_create_by :id => 'other', :name => 'Other'
  find_or_create_by :id => 'model', :name => 'Model / Dancer'
  find_or_create_by :id => 'rental', :name => 'Rental Gear'

  has_many :artists


  scope :with_icon, lambda { all }

end

app/controllers/categories_controller.rb
# == Schema Information
#
# Table name: categories
#
#  name        :string
#  id          :string           primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # # GET /categories/new
  # def new
  #   @category = Category.new
  # end
  #
  # # GET /categories/1/edit
  # def edit
  # end
  #
  # # POST /categories
  # # POST /categories.json
  # def create
  #   @category = Category.new(category_params)
  #
  #   respond_to do |format|
  #     if @category.save
  #       format.html { redirect_to @category, notice: 'Category was successfully created.' }
  #       format.json { render :show, status: :created, location: @category }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @category.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /categories/1
  # # PATCH/PUT /categories/1.json
  # def update
  #   respond_to do |format|
  #     if @category.update(category_params)
  #       format.html { redirect_to @category, notice: 'Category was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @category }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @category.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /categories/1
  # # DELETE /categories/1.json
  # def destroy
  #   @category.destroy
  #   respond_to do |format|
  #     format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :id, :description)
    end
end

app/helpers/categories_helper.rb
# == Schema Information
#
# Table name: categories
#
#  name        :string
#  id          :string           primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :id
    = f.text_field :id
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.section.categories_index
  .wrapped
    - @categories.each do |category|
      %div[category]><
        = link_to category do
          .name><= category.name

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Id:
  = @category.id
%p
  %b Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path